version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress
    web:
        image: wordpress:latest
        depends_on:
            - db
        volumes:
            - ./web:/var/www/html
        environment:
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress
            - WORDPRESS_DB_HOST=db
        ports:
            - 8080:80
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin:latest
        ports:
            - 8000:80
